### ISSUE TITLE
[Error] Workflow has been failing since 1st November

### ISSUE THREAD

**Issue by joelmathewphilip** [rohan472000/reliance-stock-price-prediction-LSTM#15]
![image](https://github.com/rohan472000/reliance-stock-price-prediction-LSTM/assets/45589731/41cd7656-6667-45c4-95ef-5afde2008404)
The workflow run has been failing since 1st November. I suspect, the PAT token expired. Re-generating a new PAT token should fix the error.

**Comment by rohan472000** [comment]
Ahh..I think that too..will change soon.
