### ISSUE TITLE
Error 403: permission denied

### ISSUE THREAD

**Issue by rohan472000** [rohan472000/reliance-stock-price-prediction-LSTM#2]
I'm trying to push and commit changes in this repo through YAML script in github workflows, but getting Error 403.

Kindly, look in this issue in `Actions`, modify it.

**Comment by Amarjit0511** [comment]
I think the problem might be with the scope selected for access tokens.

**Comment by rohan472000** [comment]
No..it's something else as I tried with token and without token also ..got same error 403

**Comment by joelmathewphilip** [comment]
@rohan472000 Created PR https://github.com/rohan472000/reliance-stock-price-prediction-LSTM/pull/8 to fix this issue. 

The documentation for git-auto-commit-action specifies this setting. 
You can find it here  https://github.com/stefanzweifel/git-auto-commit-action#:~:text=Set%20the%20contents%2Dpermission%20of%20the%20default%20GITHUB_TOKEN%20to%20true.%20(Required%20to%20push%20new%20commits%20to%20the%20repository)

#3

**Comment by rohan472000** [comment]
Kindly see the error in Actions - https://github.com/rohan472000/reliance-stock-price-prediction-LSTM/actions/runs/6364909352/job/17281520328

**Comment by joelmathewphilip** [comment]
The error is due to protection policies on the main branch, direct commits are not allowed. Are you open to creating a PAT token with the required permissions to update the main branch ?

**Comment by rohan472000** [comment]
I dont have set any rules on main.

**Comment by joelmathewphilip** [comment]
Can you confirm if the below settings are present ? 
![image](https://github.com/rohan472000/reliance-stock-price-prediction-LSTM/assets/45589731/7e9989b4-718e-474f-b258-a88fd70ddfd7)

**Comment by rohan472000** [comment]
Show me path for it quickly

**Comment by joelmathewphilip** [comment]
Settings -> General Actions
![image](https://github.com/rohan472000/reliance-stock-price-prediction-LSTM/assets/45589731/7ae2a418-9c2b-41e5-8b34-b5dc30286e46)

**Comment by rohan472000** [comment]
Done..now try again.

**Comment by rohan472000** [comment]
@joelmathewphilip 

https://github.com/rohan472000/reliance-stock-price-prediction-LSTM/actions/runs/6368460411/job/17287830383

**Comment by joelmathewphilip** [comment]
It failed. I am not sure what protection rules are triggering, as you said there is none setup. Can you create a PAT token with admin access and store it as a github secret ? Please share the secret name once you have created it.

**Comment by rohan472000** [comment]
ok...

**Comment by rohan472000** [comment]
@joelmathewphilip `ADMIN_PAT`

**Comment by rohan472000** [comment]
@joelmathewphilip kindly specify which access should be added to PAT as still access issue is there if I'm getting it correctly.

**Comment by joelmathewphilip** [comment]
@rohan472000 Now it says, even you don't have access to make changes. There is some other rule triggering in the backend
![image](https://github.com/rohan472000/reliance-stock-price-prediction-LSTM/assets/45589731/c4aa6623-88d3-4aec-910c-eb39281c767f)

**Comment by rohan472000** [comment]
wait let me make it again.

**Comment by rohan472000** [comment]
@joelmathewphilip `ADMIN_PAT`, try again.

**Comment by joelmathewphilip** [comment]
Hope the secret name is the same. Can you trigger the workflow manually ? I don't have access to do that. Otherwise, I will have to open an unwanted PR.

**Comment by rohan472000** [comment]
ok...sure

**Comment by joelmathewphilip** [comment]
It worked ! https://github.com/rohan472000/reliance-stock-price-prediction-LSTM/actions/runs/6368665366/job/17288325161

**Comment by rohan472000** [comment]
Thanks @joelmathewphilip for your contributions.

If interested then look other repo of mine, where workflows related or other potential issue is there, will appreciate your contributions.

**Comment by joelmathewphilip** [comment]
Another issue exists though. Each commit is creating a chain of github action runs, which shouldn't have happened, if we use the default github token.   
![image](https://github.com/rohan472000/reliance-stock-price-prediction-LSTM/assets/45589731/c51dd96a-53e6-4aa6-a2d7-af1026a3422d)
 I suggest disabling the trigger on the main branch for now, until we find a fix for this.

**Comment by rohan472000** [comment]
yeah ...not sure why this is happening.

**Comment by joelmathewphilip** [comment]
Please review and approve https://github.com/rohan472000/reliance-stock-price-prediction-LSTM/pull/12.

**Comment by joelmathewphilip** [comment]
Created another PR which should hopefully fix the error https://github.com/rohan472000/reliance-stock-price-prediction-LSTM/pull/13. Please review and approve

**Comment by rohan472000** [comment]
If possible, can you make a check that checks if code is doing what it expect to do without affecting main??

**Comment by joelmathewphilip** [comment]
Can you elaborate on that ?

**Comment by rohan472000** [comment]
I want to see changes a PR do on main without merging.

**Comment by joelmathewphilip** [comment]
okay, I think that can be done. Can you create a new issue for it ? As this issue is fixed

**Comment by rohan472000** [comment]
Ya sure ..

**Comment by rohan472000** [comment]
@joelmathewphilip see #14
