### ISSUE TITLE
Solution for Error 403 when using Push and Commit changes.

### ISSUE THREAD

**Issue by vedant237** [rohan472000/reliance-stock-price-prediction-LSTM#5]
1. **Authentication** :  Ensure you have the correct authentication in your workflow YAML, such as a personal access token (PAT) or appropriate credentials.

2. **Branch Permissions** :  Verify that you have permissions to push to the target branch, especially if it's protected.

3. **Repository Permissions** :  Make sure your authentication token or credentials have the required permissions for the actions you're performing.

4. **Token Scope** :  If using a PAT, confirm it has the necessary scopes, like `repo` or `workflow`.

5. **Workflow File** :  Check your workflow YAML for syntax errors or misconfigurations, especially in the steps related to checking out the repository and pushing changes.

By addressing these points, you can troubleshoot and resolve the 403 error in your GitHub Actions workflow.

Kindly Merge this Request after 1th October under the Hactoberfest Event if you got your Solution of the Problem you are facing.

**Comment by rohan472000** [comment]
> 1. **Authentication** :  Ensure you have the correct authentication in your workflow YAML, such as a personal access token (PAT) or appropriate credentials.
> 2. **Branch Permissions** :  Verify that you have permissions to push to the target branch, especially if it's protected.
> 3. **Repository Permissions** :  Make sure your authentication token or credentials have the required permissions for the actions you're performing.
> 4. **Token Scope** :  If using a PAT, confirm it has the necessary scopes, like `repo` or `workflow`.
> 5. **Workflow File** :  Check your workflow YAML for syntax errors or misconfigurations, especially in the steps related to checking out the repository and pushing changes.
> 
> By addressing these points, you can troubleshoot and resolve the 403 error in your GitHub Actions workflow.
> 
> Kindly Merge this Request after 1th October under the Hactoberfest Event if you got your Solution of the Problem you are facing.

Why advising through paragraphs , why not through code, your above mentioned points are very basic that anyone try it before raising in issue.

Kindly make PR.
