### ISSUE TITLE
adding hindi translation to the readme file

### ISSUE THREAD

**Issue by RikinR** [rohan472000/reliance-stock-price-prediction-LSTM#9]
hey it would be better if there is a hindi translation for the readme file. therefore i would like to do the translation please.

**Comment by rohan472000** [comment]
Why Hindi????

**Comment by RikinR** [comment]
because there are many people from india who use open source products and it will be helpful for them. more languages can be added but i am fluent in english and hindi.

**Comment by rohan472000** [comment]
This is not a proper reason.

**Comment by RikinR** [comment]
sure no problem.
